export { default as Login } from "./login";
export { default as Register } from "./register";
export { default as Dashboard } from "./app/dashboard";
export { default as Root } from "./root";
export { default as Verify } from "./verify";
export { default as ForgotPassword } from "./forgot-password";
export { default as ResetPassword } from "./set-password";
export { default as UnknownRoute } from "./404";
export { default as Logout } from "./logout";
