version: "3.8"

services:
  express-tracker-server:
    build: 
      context:  .
      args: 
        NODE_VERSION: 18.0.0
    image: ae5ad2782abd
    env_file: 
      - .env
    ports: 
      - 3000:3000
    depends_on:
      - db

  db: 
    image: postgres:latest
    restart: always
    env_file: 
      - .env.db
    ports: 
      - 5432:5432
    volumes: 
      - db_data:/var/lib/postgresql/data

volumes: 
  db_data: