# fly.toml app configuration file generated for expense-tracker-best on 2023-08-04T01:49:33+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "expense-tracker-best"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
