name: Health check
on: push

defaults:
  run:
    working-directory: ./
  
jobs: 
  lint-checks: 
    runs-on: ubuntu-latest

    steps: 
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install
      - name: Run typechecks
        run: yarn typecheck
      - name: Run lint checks
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
       




